import '@/app/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import { Providers } from '../providers';

const inter = Inter({ subsets: ['latin'] });

interface IAuthLayout {
  children: React.ReactNode;
  params: { locale: string };
}

export default function AuthLayout({ children, params }: IAuthLayout) {
  const { locale } = params;
  const messages = useMessages();

  return (
    <html lang={locale} className="light">
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Omega Accounts',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'site.webmanifest',
      type: 'application/json',
      url: '/site.webmanifest',
    },
    {
      rel: 'apple-touch-icon',
      url: '/apple-touch-icon.png',
    },
    {
      rel: 'android-chrome-192x192',
      type: 'image/png',
      sizes: '192x192',
      url: '/android-chrome-192x192.png',
    },
    {
      rel: 'android-chrome-512x512',
      type: 'image/png',
      sizes: '512x512',
      url: '/android-chrome-512x512.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon-32x32.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon-16x16.png',
    },
    {
      rel: 'icon',
      url: '/favicon.ico',
    },
  ],
};
