import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Providers } from './providers';
import AppFrame from '@/components/frames/AppFrame';
import { UaProvider } from '@/libs/ua-context';
import type { AppProps } from 'next/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

export default function RootLayout({ children, locale }: RootLayoutProps) {
  return (
    <html lang={locale} className="dark">
      <body className={inter.className}>
        <Providers>
          <UaProvider ua={'ua'} isMobile={false}>
            <AppFrame>{children}</AppFrame>
          </UaProvider>
        </Providers>
      </body>
    </html>
  );
}
