name: CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Type checking
      run: yarn type-check

    - name: Stylelint
      run: yarn stylelint

    - name: Run unit tests
      run: yarn test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Install Playwright (used for Storybook and E2E tests)
      run: npx playwright install --with-deps

    - name: Run storybook tests
      run: yarn test-storybook:ci

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 7

    - name: Build
      run: yarn build
