name: CI

on:
  push:
    branches: [ master, develop ]

  pull_request: 
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache yarn cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Type checking
      run: yarn type-check

    - name: Stylelint
      run: yarn stylelint

    - name: Run unit tests
      run: yarn test | tee ./coverage.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Install Playwright (used for Storybook and E2E tests)
      run: npx playwright install --with-deps

    - name: Run storybook tests
      run: yarn test-storybook:ci

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 7

    - name: Build
      run: yarn build

    - name: Jest Coverage Comment
      # We don't need to post the Jest Coverage comment on Crowdin PRs and Dependabot PRs
      # as in general they introduce no changes to the Unit Tests and the Codebase
      # We reuse the checks from the Chromatic Deploy step as they're the same conditions
      # This comments the current Jest Coverage Report containing JUnit XML reports
      # and a Code Coverage Summary
      if: |
          github.event_name == 'push' ||
          (github.event_name == 'pull_request_target' &&
            startsWith(github.event.pull_request.head.ref, 'dependabot/') == false &&
            github.event.pull_request.head.ref != 'chore/crowdin')
      uses: MishaKav/jest-coverage-comment # v1.0.25
      with:
        coverage-summary-path: ./coverage/coverage-summary.json
        title: My Jest Coverage Comment
        summary-title: My Summary Title
        badge-title: Coverage
        hide-comment: false
        create-new-comment: false
        hide-summary: false
        junitxml-title: My JUnit Title
        junitxml-path: ./coverage/junit.xml
        coverage-title: My Coverage Title
        coverage-path: ./coverage.txt
